name: Daily Firestore to BigQuery Ingestion

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: 

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Passage en v4 pour éviter le warning Node.js
      - name: Checkout code
        uses: actions/checkout@v4

      # Passage en v5 pour éviter le warning Node.js
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-cloud-firestore google-cloud-bigquery pandas db-dtypes

      - name: Run Ingestion Script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python ingestion.py
